### ISSUE TITLE
The new update fails `docker pull`

### ISSUE THREAD

**Issue by mixdf** [smoench/deptrac-action#2]
I'll attach a screenshot, which should be self-explanatory.

![image](https://user-images.githubusercontent.com/77272856/127772661-3a504683-a7d6-4ae1-b97c-afa42379ba9d.png)

**Comment by alies-dev** [comment]
I can confirm that

**Comment by smoench** [comment]
It seems that docker hub has changed and doesn't support automatic builds for accounts without any subscription. So the CI needs to be updated pushing images to docker hub instead.

**Comment by smoench** [comment]
Is working again https://hub.docker.com/layers/smoench/deptrac-action/0.14.1/images/sha256-9f441e6ec3d9f8b6a413254e0005c4fcb321c19c387c63702dd02e05ea3158c9?context=repo
